version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-axzora
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=axzora
      - N8N_BASIC_AUTH_PASSWORD=axzora2024
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - N8N_METRICS=true
      - DB_TYPE=sqlite
      - DB_SQLITE_DATABASE=/home/node/.n8n/database.sqlite
    volumes:
      - /app/n8n-data:/home/node/.n8n
      - /app/n8n-workflows:/app/workflows:ro
    command: n8n start